lib/parking_web/router.ex
defmodule ParkingWeb.Router do
  use ParkingWeb, :router

  pipeline :browser do
    plug :accepts, ["html"]
    plug :fetch_session
    plug :fetch_flash
    plug :protect_from_forgery
    plug :put_secure_browser_headers
  end

  pipeline :api do
    plug :accepts, ["json"]
  end

  pipeline :browser_auth do
    plug Parking.AuthPipeline
  end

  pipeline :ensure_auth do
    plug Guardian.Plug.EnsureAuthenticated
  end

  scope "/", ParkingWeb do
    pipe_through :browser

  end





  scope "/", ParkingWeb do
    pipe_through [:browser, :browser_auth]
    # Stuff that anybody can access
    get "/", PageController, :index
    resources "/users", UserController
    resources "/sessions", SessionController, only: [:new, :create, :delete]
    resources "/users", UserController, only: [:new, :create]
    resources "/bookings", BookingController
    get "booking/extend-page", BookingController, :extend_page
    post "booking/extend", BookingController, :extend

    get "/search", Parking_placeController ,:index
    get "/search/some", Parking_placeController ,:create
    post "/search/some", Parking_placeController ,:create
    get "/search/data", Parking_placeController ,:new
    resources "/invoices", InvoiceController

  end

  scope "/", ParkingWeb do
    pipe_through [:browser, :browser_auth, :ensure_auth]

    # Stuff only logged in users should access

  end

  # Other scopes may use custom stacks.
  # scope "/api", ParkingWeb do
  #   pipe_through :api
  # end

  # Enables LiveDashboard only for development
  #
  # If you want to use the LiveDashboard in production, you should put
  # it behind authentication and allow only admins to access it.
  # If your application does not have an admins-only section yet,
  # you can use Plug.BasicAuth to set up some basic authentication
  # as long as you are also using SSL (which you should anyway).
  if Mix.env() in [:dev, :test] do
    import Phoenix.LiveDashboard.Router

    scope "/" do
      pipe_through :browser
      live_dashboard "/dashboard", metrics: ParkingWeb.Telemetry
    end
  end
end

lib/parking_web/views/layout_view.ex
defmodule ParkingWeb.LayoutView do
  use ParkingWeb, :view
end

lib/parking_web/templates/layout/app.html.eex
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8"/>
    <meta http-equiv="X-UA-Compatible" content="IE=edge"/>
    <meta name="viewport" content="width=device-width, initial-scale=1.0"/>
    <title>Parking · Phoenix Framework</title>
    <link rel="stylesheet" href="<%= Routes.static_path(@conn, "/css/app.css") %>"/>
    <script defer type="text/javascript" src="<%= Routes.static_path(@conn, "/js/app.js") %>"></script>
  </head>
  <body>
    <header>


<nav class="navbar navbar-light bg-light justify-content-between">
  <a class="navbar-brand">ParkingApp</a>

  <%= link "Search", to: Routes.parking_place_path(@conn, :index) %>
  <%= if Parking.Authentication.load_current_user(@conn) do link "My bookings", to: Routes.booking_path(@conn, :index)  end%>
  <%= if Parking.Authentication.load_current_user(@conn) do %>
            <%= link "Invoices", to: Routes.invoice_path(@conn, :index) %>
            <%= link "Profile", to: Routes.user_path(@conn, :index), id: "Profile"%>
            <li>Hello <%= Parking.Authentication.load_current_user(@conn).name %></li>
            <li><%= link "Log out", to: Routes.session_path(@conn, :delete, Parking.Authentication.load_current_user(@conn)), method: "delete", id: "logout" %></li>
          <% else %>

          <% end %>

</nav>
    </header>
    <main role="main" class="container">
      <p class="alert alert-info" role="alert"><%= get_flash(@conn, :info) %></p>
      <p class="alert alert-danger" role="alert"><%= get_flash(@conn, :error) %></p>
      <%= @inner_content %>
    </main>

  </body>
</html>